server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ddriver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/kitty?useUnicode=true&characterEncoding=gbk&serverTimezone=UTC&autoReconnect=true
      username: wicky
      password: ht1811HT
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot admin
  application:
    name: msys-admin
  boot:
    admin:
      client:
        url: "http://localhost:8000"
        instance:
          prefer-ip: true
          service-url: "http://localhost:8088"
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql